[LFM_TRAIN_PARAMS]
EPOCHS = 20
NO_COMPONENTS = 64
LEARNING_RATE = 0.03
LOSS = "warp"
MAX_SAMPLED = 5
RANDOM_STATE = 42
MODEL_PATH = "artefacts/lfm_model.dill"
MAPPER_PATH = "artefacts/lfm_mapper.dill"

[LFM_PREDS_PARAMS]
TOP_K = 30

[CBM_TRAIN_PARAMS]
LOSS_FUNCTION = 'Logloss'
ITERATIONS = 5000
LEARNING_RATE = 0.1
DEPTH = 10
RANDOM_STATE = 1234
VERBOSE = '@bool True'
EARLY_STOPPING_ROUNDS = 100
MODEL_PATH = "artefacts/catboost_clf.cbm"